const flag = "gi";

const sharedRegex = {
    czech: new RegExp("jsem|jsi", flag),
    hungarian: new RegExp(" nem ", flag),
    slovak: new RegExp(" ako |poriadku|myslím", flag),
    slovenian: new RegExp("kaj", flag),
    albanian: new RegExp("nuk", flag),
    english: new RegExp(" the ", flag),
    french: new RegExp("c'est", flag),
    portuguese: new RegExp(" não ", flag),
    spanish: new RegExp("bien|siempre|ahora", flag),
    german: new RegExp(" das ", flag),
    italian: new RegExp(" che ", flag),
    danish: new RegExp("hvad|noget", flag),
    norwegian: new RegExp("deg", flag),
    swedish: new RegExp(" jag ", flag),
    dutch: new RegExp(" het ", flag),
    finnish: new RegExp("hän", flag),
    "serbo-croatian": new RegExp(" sam | kako ", flag),
    estonian: new RegExp("see", flag),
    icelandic: new RegExp("Það", flag),
    indonesian: new RegExp("tidak", flag),
    turkish: new RegExp(" bir ", flag),
};

module.exports = [
    { name: "polish", count: 0, utfRegex: new RegExp("się", flag), isoRegex: new RegExp("siê", flag) },
    { name: "czech", count: 0, utfRegex: sharedRegex.czech, isoRegex: sharedRegex.czech },
    { name: "hungarian", count: 0, utfRegex: sharedRegex.hungarian, isoRegex: sharedRegex.hungarian },
    { name: "romanian", count: 0, utfRegex: new RegExp("sunt|eşti", flag), isoRegex: new RegExp("sunt|eºti", flag) },
    { name: "slovak", count: 0, utfRegex: sharedRegex.slovak, isoRegex: sharedRegex.slovak },
    { name: "slovenian", count: 0, utfRegex: sharedRegex.slovenian, isoRegex: sharedRegex.slovenian },
    { name: "albanian", count: 0, utfRegex: sharedRegex.albanian, isoRegex: sharedRegex.albanian },
    { name: "russian", count: 0, utfRegex: new RegExp("что", flag), isoRegex: new RegExp("÷òî", flag) },
    { name: "ukrainian", count: 0, utfRegex: new RegExp("він|але", flag), isoRegex: new RegExp("â³í|àëå", flag) },
    { name: "bulgarian", count: 0, utfRegex: new RegExp("това|какво", flag), isoRegex: new RegExp("òîâà|äîáðå|êaêâo", flag) },
    { name: "english", count: 0, utfRegex: sharedRegex.english, isoRegex: sharedRegex.english },
    { name: "french", count: 0, utfRegex: sharedRegex.french, isoRegex: sharedRegex.french },
    { name: "portuguese", count: 0, utfRegex: sharedRegex.portuguese, isoRegex: sharedRegex.portuguese },
    { name: "spanish", count: 0, utfRegex: sharedRegex.spanish, isoRegex: sharedRegex.spanish },
    { name: "german", count: 0, utfRegex: sharedRegex.german, isoRegex: sharedRegex.german },
    { name: "italian", count: 0, utfRegex: sharedRegex.italian, isoRegex: sharedRegex.italian },
    { name: "danish", count: 0, utfRegex: sharedRegex.danish, isoRegex: sharedRegex.danish },
    { name: "norwegian", count: 0, utfRegex: sharedRegex.norwegian, isoRegex: sharedRegex.norwegian },
    { name: "swedish", count: 0, utfRegex: sharedRegex.swedish, isoRegex: sharedRegex.swedish },
    { name: "dutch", count: 0, utfRegex: sharedRegex.dutch, isoRegex: sharedRegex.dutch },
    { name: "finnish", count: 0, utfRegex: sharedRegex.finnish, isoRegex: sharedRegex.finnish },
    { name: "serbo-croatian", count: 0, utfRegex: sharedRegex["serbo-croatian"], isoRegex: sharedRegex["serbo-croatian"] },
    { name: "estonian", count: 0, utfRegex: sharedRegex.estonian, isoRegex: sharedRegex.estonian },
    { name: "icelandic", count: 0, utfRegex: sharedRegex.icelandic, isoRegex: sharedRegex.icelandic },
    { name: "indonesian", count: 0, utfRegex: sharedRegex.indonesian, isoRegex: sharedRegex.indonesian },
    { name: "greek", count: 0, utfRegex: new RegExp("είναι", flag), isoRegex: new RegExp("åßíáé", flag) },
    { name: "turkish", count: 0, utfRegex: sharedRegex.turkish, isoRegex: sharedRegex.turkish },
    { name: "hebrew", count: 0, utfRegex: new RegExp("אתה", flag), isoRegex: new RegExp("àúä", flag) },
    { name: "arabic", count: 0, utfRegex: new RegExp("هذا", flag), isoRegex: new RegExp("åðç", flag) },
    { name: "chinese-simplified", count: 0, utfRegex: new RegExp("个|人", flag), isoRegex: new RegExp("´ó|¶¯|Å®", flag) },
    { name: "chinese-traditional", count: 0, utfRegex: new RegExp("在", flag), isoRegex: new RegExp("¦b", flag) },
    { name: "japanese", count: 0, utfRegex: new RegExp("ど", flag), isoRegex: new RegExp("‚»", flag) },
    { name: "korean", count: 0, utfRegex: new RegExp("도", flag), isoRegex: new RegExp("àö¾î|å¾ß|¡¼­", flag) },
    { name: "thai", count: 0, utfRegex: new RegExp("แฮร์รี่|พอตเตอร์", flag), isoRegex: new RegExp("áîãìãõè|¾íµàµíãì­", flag) }
];