const flag = "gi";

const sharedRegex = {
    czech: new RegExp("jsem|jsi", flag),
    hungarian: new RegExp(" nem ", flag),
    slovak: new RegExp(" ako |poriadku|myslím", flag),
    slovenian: new RegExp("kaj", flag),
    albanian: new RegExp("nuk", flag),
    english: new RegExp(" the ", flag),
    french: new RegExp("c'est", flag),
    portuguese: new RegExp(" não ", flag),
    spanish: new RegExp("bien|siempre|ahora", flag),
};

module.exports = [
    { name: "polish", count: 0, utfRegex: new RegExp("się", flag), isoRegex: new RegExp("siê", flag) },
    { name: "czech", count: 0, utfRegex: sharedRegex.czech, isoRegex: sharedRegex.czech },
    { name: "hungarian", count: 0, utfRegex: sharedRegex.hungarian, isoRegex: sharedRegex.hungarian },
    { name: "romanian", count: 0, utfRegex: new RegExp("sunt|eşti", flag), isoRegex: new RegExp("sunt|eºti", flag) },
    { name: "slovak", count: 0, utfRegex: sharedRegex.slovak, isoRegex: sharedRegex.slovak },
    { name: "slovenian", count: 0, utfRegex: sharedRegex.slovenian, isoRegex: sharedRegex.slovenian },
    { name: "albanian", count: 0, utfRegex: sharedRegex.albanian, isoRegex: sharedRegex.albanian },
    { name: "russian", count: 0, utfRegex: new RegExp("что", flag), isoRegex: new RegExp("÷òî", flag) },
    { name: "ukrainian", count: 0, utfRegex: new RegExp("він|але", flag), isoRegex: new RegExp("â³í|àëå", flag) },
    { name: "bulgarian", count: 0, utfRegex: new RegExp("това|какво", flag), isoRegex: new RegExp("òîâà|äîáðå|êaêâo", flag) },
    { name: "english", count: 0, utfRegex: sharedRegex.english, isoRegex: sharedRegex.english },
    { name: "french", count: 0, utfRegex: sharedRegex.french, isoRegex: sharedRegex.french },
    { name: "portuguese", count: 0, utfRegex: sharedRegex.portuguese, isoRegex: sharedRegex.portuguese },
    { name: "spanish", count: 0, utfRegex: sharedRegex.spanish, isoRegex: sharedRegex.spanish },
    // german: 0,
    // italian: 0,
    // danish: 0,
    // norwegian: 0,
    // swedish: 0,
    // dutch: 0,
    // finnish: 0,
    // "serbo-croatian": 0,
    // estonian: 0,
    // icelandic: 0,
    // indonesian: 0,
    // greek: 0,
    // turkish: 0,
    // hebrew: 0,
    // arabic: 0,
    // "chinese-simplified": 0,
    // "chinese-traditional": 0,
    // japanese: 0,
    // korean: 0,
    // thai: 0
];